### ISSUE TITLE
Search results state not preserved on page navigation 

### ISSUE THREAD

**Issue by Collinson165** [Collinson165/Movie-Search-App#1]
**Description**:
**Steps to Reproduce**:
1. Navigate to the home page of the app.
2. Perform a search using the search bar.
3. Observe the search results that are displayed.
4. Click on a search result to navigate to a different page.
5. Use the browser's back button to return to the home page.
6. Notice that the search results are no longer displayed.

**Expected Behavior**:
When I navigate back to the home page after clicking on a search result, the search results should still be visible.

**Current Behavior**:
The search results disappear when I navigate back to the home page.

**Additional Information**:
- The app uses React Router for navigation.
- I suspect that the lack of state management (such as Redux or the Context API) could be causing the issue.
- This behavior is consistent across different browsers.

**Environment**:
- React version: 18.2.0
- React Router version: 6.3.0

**Labels**: bug, needs investigation

**Assignees**: [Collinson165]

**Comment by AdityaAB4** [comment]
I want to work on this issue.

**Comment by Collinson165** [comment]
> I want to work on this issue.

Thank you for expressing interest in contributing to this project. If you have any issue as you work on this, don't hesitate to reach out. Happy coding

**Comment by Collinson165** [comment]
This issue has been resolved by pull request #3 and is now closed. Thanks to @AdityaAB4 for their contribution
